// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Codes defines model for Codes.
type Codes = string

// Delay defines model for Delay.
type Delay = string

// ETag defines model for ETag.
type ETag = string

// N defines model for N.
type N = int

// Name defines model for Name.
type Name = string

// Offset defines model for Offset.
type Offset = int

// Password defines model for Password.
type Password = string

// Path defines model for Path.
type Path = string

// Seconds defines model for Seconds.
type Seconds = int

// User defines model for User.
type User = string

// Value defines model for Value.
type Value = string

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /)
	Index(w http.ResponseWriter, r *http.Request)

	// (GET /absolute-redirect/{n})
	AbsoluteRedirect(w http.ResponseWriter, r *http.Request, n N)

	// (DELETE /anything)
	AnythingDelete(w http.ResponseWriter, r *http.Request)

	// (GET /anything)
	AnythingGet(w http.ResponseWriter, r *http.Request)

	// (PATCH /anything)
	AnythingPatch(w http.ResponseWriter, r *http.Request)

	// (POST /anything)
	AnythingPost(w http.ResponseWriter, r *http.Request)

	// (PUT /anything)
	AnythingPut(w http.ResponseWriter, r *http.Request)

	// (DELETE /anything/{path})
	AnythingPathDelete(w http.ResponseWriter, r *http.Request, path Path)

	// (GET /anything/{path})
	AnythingPathGet(w http.ResponseWriter, r *http.Request, path Path)

	// (PATCH /anything/{path})
	AnythingPathPatch(w http.ResponseWriter, r *http.Request, path Path)

	// (POST /anything/{path})
	AnythingPathPost(w http.ResponseWriter, r *http.Request, path Path)

	// (PUT /anything/{path})
	AnythingPathPut(w http.ResponseWriter, r *http.Request, path Path)

	// (GET /base64/{value})
	Base64Decode(w http.ResponseWriter, r *http.Request, value Value)

	// (GET /basic-auth/{user}/{password})
	BasicAuth(w http.ResponseWriter, r *http.Request, user User, password Password)

	// (GET /bearer)
	Bearer(w http.ResponseWriter, r *http.Request)

	// (GET /bytes/{n})
	Bytes(w http.ResponseWriter, r *http.Request, n N)

	// (GET /cache)
	Cache(w http.ResponseWriter, r *http.Request)

	// (GET /cache/{seconds})
	CacheSeconds(w http.ResponseWriter, r *http.Request, seconds Seconds)

	// (GET /cookies)
	Cookies(w http.ResponseWriter, r *http.Request)

	// (GET /cookies/delete)
	DeleteCookies(w http.ResponseWriter, r *http.Request)

	// (GET /cookies/set)
	SetCookiesFromQuery(w http.ResponseWriter, r *http.Request)

	// (GET /cookies/set/{name}/{value})
	SetCookie(w http.ResponseWriter, r *http.Request, name Name, value Value)

	// (GET /deflate)
	Deflate(w http.ResponseWriter, r *http.Request)

	// (GET /delay/{delay})
	Delay(w http.ResponseWriter, r *http.Request, delay Delay)

	// (DELETE /delete)
	DeleteEcho(w http.ResponseWriter, r *http.Request)

	// (GET /deny)
	Deny(w http.ResponseWriter, r *http.Request)

	// (GET /docs)
	Docs(w http.ResponseWriter, r *http.Request)

	// (GET /drip)
	Drip(w http.ResponseWriter, r *http.Request)

	// (GET /encoding/utf8)
	UTF8(w http.ResponseWriter, r *http.Request)

	// (GET /etag/{etag})
	ETag(w http.ResponseWriter, r *http.Request, etag ETag)

	// (GET /get)
	GetEcho(w http.ResponseWriter, r *http.Request)

	// (GET /gzip)
	Gzip(w http.ResponseWriter, r *http.Request)

	// (GET /headers)
	Headers(w http.ResponseWriter, r *http.Request)

	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)

	// (GET /hidden-basic-auth/{user}/{password})
	HiddenBasicAuth(w http.ResponseWriter, r *http.Request, user User, password Password)

	// (GET /html)
	HTML(w http.ResponseWriter, r *http.Request)

	// (GET /image)
	Image(w http.ResponseWriter, r *http.Request)

	// (GET /image/gif)
	ImageGIF(w http.ResponseWriter, r *http.Request)

	// (GET /image/jpeg)
	ImageJPEG(w http.ResponseWriter, r *http.Request)

	// (GET /image/png)
	ImagePNG(w http.ResponseWriter, r *http.Request)

	// (GET /image/svg)
	ImageSVG(w http.ResponseWriter, r *http.Request)

	// (GET /ip)
	IP(w http.ResponseWriter, r *http.Request)

	// (GET /json)
	JSON(w http.ResponseWriter, r *http.Request)

	// (GET /links/{n}/{offset})
	Links(w http.ResponseWriter, r *http.Request, n N, offset Offset)

	// (GET /openapi.yaml)
	OpenAPIYAML(w http.ResponseWriter, r *http.Request)

	// (PATCH /patch)
	PatchEcho(w http.ResponseWriter, r *http.Request)

	// (POST /post)
	PostEcho(w http.ResponseWriter, r *http.Request)

	// (PUT /put)
	PutEcho(w http.ResponseWriter, r *http.Request)

	// (GET /readyz)
	Readyz(w http.ResponseWriter, r *http.Request)

	// (GET /redirect-to)
	RedirectTo(w http.ResponseWriter, r *http.Request)

	// (GET /redirect/{n})
	Redirect(w http.ResponseWriter, r *http.Request, n N)

	// (GET /relative-redirect/{n})
	RelativeRedirect(w http.ResponseWriter, r *http.Request, n N)

	// (GET /response-headers)
	ResponseHeadersGet(w http.ResponseWriter, r *http.Request)

	// (POST /response-headers)
	ResponseHeadersPost(w http.ResponseWriter, r *http.Request)

	// (GET /robots.txt)
	Robots(w http.ResponseWriter, r *http.Request)

	// (DELETE /status/{codes})
	StatusDelete(w http.ResponseWriter, r *http.Request, codes Codes)

	// (GET /status/{codes})
	StatusGet(w http.ResponseWriter, r *http.Request, codes Codes)

	// (POST /status/{codes})
	StatusPost(w http.ResponseWriter, r *http.Request, codes Codes)

	// (PUT /status/{codes})
	StatusPut(w http.ResponseWriter, r *http.Request, codes Codes)

	// (GET /stream-bytes/{n})
	StreamBytes(w http.ResponseWriter, r *http.Request, n N)

	// (GET /stream/{n})
	Stream(w http.ResponseWriter, r *http.Request, n N)

	// (GET /user-agent)
	UserAgent(w http.ResponseWriter, r *http.Request)

	// (GET /uuid)
	UUID(w http.ResponseWriter, r *http.Request)

	// (GET /xml)
	XML(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /)
func (_ Unimplemented) Index(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /absolute-redirect/{n})
func (_ Unimplemented) AbsoluteRedirect(w http.ResponseWriter, r *http.Request, n N) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /anything)
func (_ Unimplemented) AnythingDelete(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /anything)
func (_ Unimplemented) AnythingGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /anything)
func (_ Unimplemented) AnythingPatch(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /anything)
func (_ Unimplemented) AnythingPost(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /anything)
func (_ Unimplemented) AnythingPut(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /anything/{path})
func (_ Unimplemented) AnythingPathDelete(w http.ResponseWriter, r *http.Request, path Path) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /anything/{path})
func (_ Unimplemented) AnythingPathGet(w http.ResponseWriter, r *http.Request, path Path) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /anything/{path})
func (_ Unimplemented) AnythingPathPatch(w http.ResponseWriter, r *http.Request, path Path) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /anything/{path})
func (_ Unimplemented) AnythingPathPost(w http.ResponseWriter, r *http.Request, path Path) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /anything/{path})
func (_ Unimplemented) AnythingPathPut(w http.ResponseWriter, r *http.Request, path Path) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /base64/{value})
func (_ Unimplemented) Base64Decode(w http.ResponseWriter, r *http.Request, value Value) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /basic-auth/{user}/{password})
func (_ Unimplemented) BasicAuth(w http.ResponseWriter, r *http.Request, user User, password Password) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /bearer)
func (_ Unimplemented) Bearer(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /bytes/{n})
func (_ Unimplemented) Bytes(w http.ResponseWriter, r *http.Request, n N) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /cache)
func (_ Unimplemented) Cache(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /cache/{seconds})
func (_ Unimplemented) CacheSeconds(w http.ResponseWriter, r *http.Request, seconds Seconds) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /cookies)
func (_ Unimplemented) Cookies(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /cookies/delete)
func (_ Unimplemented) DeleteCookies(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /cookies/set)
func (_ Unimplemented) SetCookiesFromQuery(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /cookies/set/{name}/{value})
func (_ Unimplemented) SetCookie(w http.ResponseWriter, r *http.Request, name Name, value Value) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /deflate)
func (_ Unimplemented) Deflate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /delay/{delay})
func (_ Unimplemented) Delay(w http.ResponseWriter, r *http.Request, delay Delay) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /delete)
func (_ Unimplemented) DeleteEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /deny)
func (_ Unimplemented) Deny(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /docs)
func (_ Unimplemented) Docs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /drip)
func (_ Unimplemented) Drip(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /encoding/utf8)
func (_ Unimplemented) UTF8(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /etag/{etag})
func (_ Unimplemented) ETag(w http.ResponseWriter, r *http.Request, etag ETag) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /get)
func (_ Unimplemented) GetEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /gzip)
func (_ Unimplemented) Gzip(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /headers)
func (_ Unimplemented) Headers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /healthz)
func (_ Unimplemented) Healthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /hidden-basic-auth/{user}/{password})
func (_ Unimplemented) HiddenBasicAuth(w http.ResponseWriter, r *http.Request, user User, password Password) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /html)
func (_ Unimplemented) HTML(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /image)
func (_ Unimplemented) Image(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /image/gif)
func (_ Unimplemented) ImageGIF(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /image/jpeg)
func (_ Unimplemented) ImageJPEG(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /image/png)
func (_ Unimplemented) ImagePNG(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /image/svg)
func (_ Unimplemented) ImageSVG(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ip)
func (_ Unimplemented) IP(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /json)
func (_ Unimplemented) JSON(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /links/{n}/{offset})
func (_ Unimplemented) Links(w http.ResponseWriter, r *http.Request, n N, offset Offset) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /openapi.yaml)
func (_ Unimplemented) OpenAPIYAML(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /patch)
func (_ Unimplemented) PatchEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /post)
func (_ Unimplemented) PostEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /put)
func (_ Unimplemented) PutEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /readyz)
func (_ Unimplemented) Readyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /redirect-to)
func (_ Unimplemented) RedirectTo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /redirect/{n})
func (_ Unimplemented) Redirect(w http.ResponseWriter, r *http.Request, n N) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /relative-redirect/{n})
func (_ Unimplemented) RelativeRedirect(w http.ResponseWriter, r *http.Request, n N) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /response-headers)
func (_ Unimplemented) ResponseHeadersGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /response-headers)
func (_ Unimplemented) ResponseHeadersPost(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /robots.txt)
func (_ Unimplemented) Robots(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /status/{codes})
func (_ Unimplemented) StatusDelete(w http.ResponseWriter, r *http.Request, codes Codes) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /status/{codes})
func (_ Unimplemented) StatusGet(w http.ResponseWriter, r *http.Request, codes Codes) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /status/{codes})
func (_ Unimplemented) StatusPost(w http.ResponseWriter, r *http.Request, codes Codes) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /status/{codes})
func (_ Unimplemented) StatusPut(w http.ResponseWriter, r *http.Request, codes Codes) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /stream-bytes/{n})
func (_ Unimplemented) StreamBytes(w http.ResponseWriter, r *http.Request, n N) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /stream/{n})
func (_ Unimplemented) Stream(w http.ResponseWriter, r *http.Request, n N) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /user-agent)
func (_ Unimplemented) UserAgent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /uuid)
func (_ Unimplemented) UUID(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /xml)
func (_ Unimplemented) XML(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Index operation middleware
func (siw *ServerInterfaceWrapper) Index(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Index(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AbsoluteRedirect operation middleware
func (siw *ServerInterfaceWrapper) AbsoluteRedirect(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "n" -------------
	var n N

	err = runtime.BindStyledParameterWithOptions("simple", "n", chi.URLParam(r, "n"), &n, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "n", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AbsoluteRedirect(w, r, n)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnythingDelete operation middleware
func (siw *ServerInterfaceWrapper) AnythingDelete(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnythingDelete(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnythingGet operation middleware
func (siw *ServerInterfaceWrapper) AnythingGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnythingGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnythingPatch operation middleware
func (siw *ServerInterfaceWrapper) AnythingPatch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnythingPatch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnythingPost operation middleware
func (siw *ServerInterfaceWrapper) AnythingPost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnythingPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnythingPut operation middleware
func (siw *ServerInterfaceWrapper) AnythingPut(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnythingPut(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnythingPathDelete operation middleware
func (siw *ServerInterfaceWrapper) AnythingPathDelete(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path Path

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnythingPathDelete(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnythingPathGet operation middleware
func (siw *ServerInterfaceWrapper) AnythingPathGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path Path

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnythingPathGet(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnythingPathPatch operation middleware
func (siw *ServerInterfaceWrapper) AnythingPathPatch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path Path

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnythingPathPatch(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnythingPathPost operation middleware
func (siw *ServerInterfaceWrapper) AnythingPathPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path Path

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnythingPathPost(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnythingPathPut operation middleware
func (siw *ServerInterfaceWrapper) AnythingPathPut(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path Path

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnythingPathPut(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Base64Decode operation middleware
func (siw *ServerInterfaceWrapper) Base64Decode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "value" -------------
	var value Value

	err = runtime.BindStyledParameterWithOptions("simple", "value", chi.URLParam(r, "value"), &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "value", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Base64Decode(w, r, value)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BasicAuth operation middleware
func (siw *ServerInterfaceWrapper) BasicAuth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user" -------------
	var user User

	err = runtime.BindStyledParameterWithOptions("simple", "user", chi.URLParam(r, "user"), &user, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user", Err: err})
		return
	}

	// ------------- Path parameter "password" -------------
	var password Password

	err = runtime.BindStyledParameterWithOptions("simple", "password", chi.URLParam(r, "password"), &password, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "password", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BasicAuth(w, r, user, password)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Bearer operation middleware
func (siw *ServerInterfaceWrapper) Bearer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Bearer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Bytes operation middleware
func (siw *ServerInterfaceWrapper) Bytes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "n" -------------
	var n N

	err = runtime.BindStyledParameterWithOptions("simple", "n", chi.URLParam(r, "n"), &n, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "n", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Bytes(w, r, n)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Cache operation middleware
func (siw *ServerInterfaceWrapper) Cache(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Cache(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CacheSeconds operation middleware
func (siw *ServerInterfaceWrapper) CacheSeconds(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seconds" -------------
	var seconds Seconds

	err = runtime.BindStyledParameterWithOptions("simple", "seconds", chi.URLParam(r, "seconds"), &seconds, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seconds", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CacheSeconds(w, r, seconds)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Cookies operation middleware
func (siw *ServerInterfaceWrapper) Cookies(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Cookies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCookies operation middleware
func (siw *ServerInterfaceWrapper) DeleteCookies(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCookies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetCookiesFromQuery operation middleware
func (siw *ServerInterfaceWrapper) SetCookiesFromQuery(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetCookiesFromQuery(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetCookie operation middleware
func (siw *ServerInterfaceWrapper) SetCookie(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "value" -------------
	var value Value

	err = runtime.BindStyledParameterWithOptions("simple", "value", chi.URLParam(r, "value"), &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "value", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetCookie(w, r, name, value)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Deflate operation middleware
func (siw *ServerInterfaceWrapper) Deflate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Deflate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Delay operation middleware
func (siw *ServerInterfaceWrapper) Delay(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "delay" -------------
	var delay Delay

	err = runtime.BindStyledParameterWithOptions("simple", "delay", chi.URLParam(r, "delay"), &delay, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "delay", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Delay(w, r, delay)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEcho operation middleware
func (siw *ServerInterfaceWrapper) DeleteEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Deny operation middleware
func (siw *ServerInterfaceWrapper) Deny(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Deny(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Docs operation middleware
func (siw *ServerInterfaceWrapper) Docs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Docs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Drip operation middleware
func (siw *ServerInterfaceWrapper) Drip(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Drip(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UTF8 operation middleware
func (siw *ServerInterfaceWrapper) UTF8(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UTF8(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ETag operation middleware
func (siw *ServerInterfaceWrapper) ETag(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "etag" -------------
	var etag ETag

	err = runtime.BindStyledParameterWithOptions("simple", "etag", chi.URLParam(r, "etag"), &etag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "etag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ETag(w, r, etag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEcho operation middleware
func (siw *ServerInterfaceWrapper) GetEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Gzip operation middleware
func (siw *ServerInterfaceWrapper) Gzip(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Gzip(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Headers operation middleware
func (siw *ServerInterfaceWrapper) Headers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Headers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HiddenBasicAuth operation middleware
func (siw *ServerInterfaceWrapper) HiddenBasicAuth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user" -------------
	var user User

	err = runtime.BindStyledParameterWithOptions("simple", "user", chi.URLParam(r, "user"), &user, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user", Err: err})
		return
	}

	// ------------- Path parameter "password" -------------
	var password Password

	err = runtime.BindStyledParameterWithOptions("simple", "password", chi.URLParam(r, "password"), &password, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "password", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HiddenBasicAuth(w, r, user, password)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HTML operation middleware
func (siw *ServerInterfaceWrapper) HTML(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HTML(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Image operation middleware
func (siw *ServerInterfaceWrapper) Image(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Image(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImageGIF operation middleware
func (siw *ServerInterfaceWrapper) ImageGIF(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImageGIF(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImageJPEG operation middleware
func (siw *ServerInterfaceWrapper) ImageJPEG(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImageJPEG(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImagePNG operation middleware
func (siw *ServerInterfaceWrapper) ImagePNG(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImagePNG(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImageSVG operation middleware
func (siw *ServerInterfaceWrapper) ImageSVG(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImageSVG(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IP operation middleware
func (siw *ServerInterfaceWrapper) IP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JSON operation middleware
func (siw *ServerInterfaceWrapper) JSON(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JSON(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Links operation middleware
func (siw *ServerInterfaceWrapper) Links(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "n" -------------
	var n N

	err = runtime.BindStyledParameterWithOptions("simple", "n", chi.URLParam(r, "n"), &n, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "n", Err: err})
		return
	}

	// ------------- Path parameter "offset" -------------
	var offset Offset

	err = runtime.BindStyledParameterWithOptions("simple", "offset", chi.URLParam(r, "offset"), &offset, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Links(w, r, n, offset)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OpenAPIYAML operation middleware
func (siw *ServerInterfaceWrapper) OpenAPIYAML(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OpenAPIYAML(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchEcho operation middleware
func (siw *ServerInterfaceWrapper) PatchEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEcho operation middleware
func (siw *ServerInterfaceWrapper) PostEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutEcho operation middleware
func (siw *ServerInterfaceWrapper) PutEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedirectTo operation middleware
func (siw *ServerInterfaceWrapper) RedirectTo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedirectTo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Redirect operation middleware
func (siw *ServerInterfaceWrapper) Redirect(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "n" -------------
	var n N

	err = runtime.BindStyledParameterWithOptions("simple", "n", chi.URLParam(r, "n"), &n, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "n", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Redirect(w, r, n)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RelativeRedirect operation middleware
func (siw *ServerInterfaceWrapper) RelativeRedirect(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "n" -------------
	var n N

	err = runtime.BindStyledParameterWithOptions("simple", "n", chi.URLParam(r, "n"), &n, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "n", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RelativeRedirect(w, r, n)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResponseHeadersGet operation middleware
func (siw *ServerInterfaceWrapper) ResponseHeadersGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResponseHeadersGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResponseHeadersPost operation middleware
func (siw *ServerInterfaceWrapper) ResponseHeadersPost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResponseHeadersPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Robots operation middleware
func (siw *ServerInterfaceWrapper) Robots(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Robots(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StatusDelete operation middleware
func (siw *ServerInterfaceWrapper) StatusDelete(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "codes" -------------
	var codes Codes

	err = runtime.BindStyledParameterWithOptions("simple", "codes", chi.URLParam(r, "codes"), &codes, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "codes", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StatusDelete(w, r, codes)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StatusGet operation middleware
func (siw *ServerInterfaceWrapper) StatusGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "codes" -------------
	var codes Codes

	err = runtime.BindStyledParameterWithOptions("simple", "codes", chi.URLParam(r, "codes"), &codes, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "codes", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StatusGet(w, r, codes)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StatusPost operation middleware
func (siw *ServerInterfaceWrapper) StatusPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "codes" -------------
	var codes Codes

	err = runtime.BindStyledParameterWithOptions("simple", "codes", chi.URLParam(r, "codes"), &codes, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "codes", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StatusPost(w, r, codes)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StatusPut operation middleware
func (siw *ServerInterfaceWrapper) StatusPut(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "codes" -------------
	var codes Codes

	err = runtime.BindStyledParameterWithOptions("simple", "codes", chi.URLParam(r, "codes"), &codes, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "codes", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StatusPut(w, r, codes)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamBytes operation middleware
func (siw *ServerInterfaceWrapper) StreamBytes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "n" -------------
	var n N

	err = runtime.BindStyledParameterWithOptions("simple", "n", chi.URLParam(r, "n"), &n, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "n", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamBytes(w, r, n)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Stream operation middleware
func (siw *ServerInterfaceWrapper) Stream(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "n" -------------
	var n N

	err = runtime.BindStyledParameterWithOptions("simple", "n", chi.URLParam(r, "n"), &n, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "n", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Stream(w, r, n)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserAgent operation middleware
func (siw *ServerInterfaceWrapper) UserAgent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UUID operation middleware
func (siw *ServerInterfaceWrapper) UUID(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UUID(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// XML operation middleware
func (siw *ServerInterfaceWrapper) XML(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.XML(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.Index)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/absolute-redirect/{n}", wrapper.AbsoluteRedirect)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/anything", wrapper.AnythingDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/anything", wrapper.AnythingGet)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/anything", wrapper.AnythingPatch)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/anything", wrapper.AnythingPost)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/anything", wrapper.AnythingPut)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/anything/{path}", wrapper.AnythingPathDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/anything/{path}", wrapper.AnythingPathGet)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/anything/{path}", wrapper.AnythingPathPatch)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/anything/{path}", wrapper.AnythingPathPost)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/anything/{path}", wrapper.AnythingPathPut)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/base64/{value}", wrapper.Base64Decode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/basic-auth/{user}/{password}", wrapper.BasicAuth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bearer", wrapper.Bearer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bytes/{n}", wrapper.Bytes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cache", wrapper.Cache)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cache/{seconds}", wrapper.CacheSeconds)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cookies", wrapper.Cookies)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cookies/delete", wrapper.DeleteCookies)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cookies/set", wrapper.SetCookiesFromQuery)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cookies/set/{name}/{value}", wrapper.SetCookie)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deflate", wrapper.Deflate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/delay/{delay}", wrapper.Delay)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/delete", wrapper.DeleteEcho)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deny", wrapper.Deny)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/docs", wrapper.Docs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/drip", wrapper.Drip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/encoding/utf8", wrapper.UTF8)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/etag/{etag}", wrapper.ETag)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/get", wrapper.GetEcho)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/gzip", wrapper.Gzip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/headers", wrapper.Headers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Healthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/hidden-basic-auth/{user}/{password}", wrapper.HiddenBasicAuth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/html", wrapper.HTML)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/image", wrapper.Image)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/image/gif", wrapper.ImageGIF)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/image/jpeg", wrapper.ImageJPEG)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/image/png", wrapper.ImagePNG)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/image/svg", wrapper.ImageSVG)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ip", wrapper.IP)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/json", wrapper.JSON)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/links/{n}/{offset}", wrapper.Links)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/openapi.yaml", wrapper.OpenAPIYAML)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/patch", wrapper.PatchEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/post", wrapper.PostEcho)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/put", wrapper.PutEcho)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.Readyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/redirect-to", wrapper.RedirectTo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/redirect/{n}", wrapper.Redirect)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/relative-redirect/{n}", wrapper.RelativeRedirect)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/response-headers", wrapper.ResponseHeadersGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/response-headers", wrapper.ResponseHeadersPost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/robots.txt", wrapper.Robots)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/status/{codes}", wrapper.StatusDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/status/{codes}", wrapper.StatusGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/status/{codes}", wrapper.StatusPost)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/status/{codes}", wrapper.StatusPut)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stream-bytes/{n}", wrapper.StreamBytes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stream/{n}", wrapper.Stream)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user-agent", wrapper.UserAgent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/uuid", wrapper.UUID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/xml", wrapper.XML)
	})

	return r
}
